.include "../../mk/top.mk"

STAGE_COPY += include/bib/bib.h
STAGE_COPY += include/bib/debug.h
STAGE_COPY += include/bib/find.h
STAGE_COPY += include/bib/free.h
STAGE_COPY += include/bib/lex.h
STAGE_COPY += include/bib/out.h
STAGE_COPY += include/bib/refactor.h

