.include "../mk/top.mk"

GEN += lib/parser.c

SRC += lib/lex.c
SRC += lib/bib.c
SRC += lib/refactor.c
SRC += lib/find.c
SRC += lib/split.c
SRC += lib/merge.c
SRC += lib/cull.c

PARSER += lib/parser.sid

